language: php
sudo: false
php:
  - 5.5

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script: phpunit --configuration .phpunit.xml

notifications:
  email: false
  irc:
    on_success: never
    on_failure: always
    channels:
      - "chat.freenode.net#steamlug"
    template:
      - "[%{repository_name}] %{commit} by %{author}: %{message}"
      - "[%{repository_name}] Build details: %{build_url}"

install:
    - composer require seld/jsonlint:1.3.1
